title: Your awesome title
email: your-email@domain.com
author: GitHub User

# Copyright setting
# You can use any html code, currently below placeholders are available:
current year: {currentYear}
author: {author} (Value is the same as site.author)
copyright: (c) - ©
copyleft: (cleft)
sound recording copyright: (p) - ℗
theme: jekyll-theme-cayman
baseurl: "/docs"
categories: jekyll update
markdown: kramdown
header_pages:
  - HAMK_BASIC_Software_Chocolatey_BYOD.md
  - index1.md