title: HAMK BYOD
#to hide view on github page
author: Deepak KC
github:
  is_project_page: false
theme: jekyll-theme-cayman
#remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: "OS22"
show_downloads: false
