title: Your awesome title
email: your-email@domain.com
author: GitHub User

# Copyright setting
# You can use any html code, currently below placeholders are available:
theme: jekyll-theme-cayman
baseurl: "OS22"

