title: HAMK BYOD
email: your-email@domain.com
author: Deepak KC
#to hide view on github page
github:
  is_project_page: false
#theme: jekyll-theme-cayman
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: "OS22"

